apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workload-pool
  labels:
    app: workload-pool
    kubedirect/workload-pool: trace
spec:
  selector:
    matchLabels:
      app: workload-pool
      kubedirect/workload-pool: trace
  template:
    metadata:
      labels:
        app: workload-pool
        kubedirect/workload-pool: trace
    spec:
      automountServiceAccountToken: false
      containers:
      - name: workload-pool
        image: ghcr.io/vhive-serverless/invitro_trace_function:latest
        # NOTE: always use the latest image
        imagePullPolicy: Always
        ports:
        - name: h2c
          containerPort: 80
        env:
        - name: ITERATIONS_MULTIPLIER
          # values copied from Dirigent AE
          # https://github.com/vhive-serverless/invitro/blob/0b0d6d7ee59e820a2472a568c89740e0ad157b69/workloads/container/trace_func_go.yaml#L31
          value: "102"
        - name: FUNCTION_TYPE
          value: "trace"
